name = "gate"
main = "src/index.ts"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat"]
keep_vars = true

[[d1_databases]]
binding = "GateDB"
database_name = "GateDB"
database_id = "f0dc7796-6f12-435c-a7f7-63652ef29857"

[env.dev]
vars = { ENVIRONMENT = "development" }
route = { pattern = "gate.dev.yebuntu.com", custom_domain = true }

[env.production]
vars = { ENVIRONMENT = "production" }
route = { pattern = "gate.yebuntu.com", custom_domain = true}
logpush = true