name = "gate"
main = "src/index.ts"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat" ]

[vars]
AUTHENTICATION_TOKEN = "66Sd6bz3LSqOgU8BOqPPXFshJAD5nZnVZfhWV55DxHE="

[[durable_objects.bindings]]
name = "GateStorage"
class_name = "GateStorage"

[[durable_objects.bindings]]
name = "RateLimitStorage"
class_name = "RateLimitStorage"

[[migrations]]
tag = "v1"
new_classes = ["GateStorage", "RateLimitStorage"]
